import { useState } from 'react';
import Modal from '../../../components/common/Modal';
import PeopleTable from '../components/PeopleTable';
import { userSchema, validationMessage } from '../../../validation/schemas';
import peopleService from '../people.service';
import { hasPermission } from '../../../utils/permissions';

export default function PeopleList({ user, users, tenants, permissions, onRefresh }) {
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState(null); const [error, setError] = useState(''); const role = user.role === 'SUPER_ADMIN' ? 'ADMIN' : 'AGENT';
  const canManagePermissions = hasPermission(user, 'permissions.manage');
  const projectPermissions = permissions.filter((item) => item.key.startsWith('projects.'));
  async function create(event) { event.preventDefault(); const form = new FormData(event.currentTarget); const result = userSchema.safeParse({ name: form.get('name'), email: form.get('email'), password: form.get('password'), tenantId: user.role === 'SUPER_ADMIN' ? form.get('tenantId') : user.tenantId, permissions: canManagePermissions ? projectPermissions.map((item) => item.key).filter((key) => form.get(`perm-${key}`) === 'on') : [] }); if (!result.success) { setError(validationMessage(result)); return; } try { await peopleService.create({ ...result.data, role }); setOpen(false); await onRefresh(); } catch (err) { setError(err.message); } }
  async function toggle(target) { try { await peopleService.updateStatus(target.id, !target.isActive); await onRefresh(); } catch (err) { setError(err.message); } }
  async function save(event) { event.preventDefault(); const selected = projectPermissions.map((item) => item.key).filter((key) => event.currentTarget.elements[`perm-${key}`]?.checked); try { await peopleService.setPermissions(editing.id, selected); setEditing(null); await onRefresh(); } catch (err) { setError(err.message); } }
  return <><section className="page-heading"><div><p className="eyebrow">Team management</p><h1>People</h1><p className="muted">{user.role === 'SUPER_ADMIN' ? 'Manage all users across tenants.' : 'Create, update, enable, and disable Agents in your workspace.'}</p></div><button className="primary-button" onClick={() => setOpen(true)}><span>＋</span> Create {role === 'ADMIN' ? 'admin' : 'agent'}</button></section>{error && <p className="banner-error">{error}</p>}<PeopleTable currentUser={user} users={users} onToggle={toggle} onPermissions={canManagePermissions ? setEditing : undefined} />{open && <Modal title={`Create ${role.toLowerCase()}`} onClose={() => setOpen(false)}><form onSubmit={create}><label>Name<input name="name" required /></label><label>Email<input name="email" type="email" required /></label><label>Password<input name="password" type="password" minLength={8} required /></label>{user.role === 'SUPER_ADMIN' && <label>Tenant<select name="tenantId" defaultValue=""><option value="">Unassigned</option>{tenants.map((tenant) => <option key={tenant.id} value={tenant.id}>{tenant.name}</option>)}</select></label>}{role === 'AGENT' && canManagePermissions && <fieldset className="perm-fieldset"><legend>Project permissions</legend>{projectPermissions.map((item) => <label className="checkbox-label" key={item.key}><input type="checkbox" name={`perm-${item.key}`} />{item.label}</label>)}</fieldset>}<button className="primary-button" type="submit">Create user</button></form></Modal>}{editing && canManagePermissions && <Modal title="Manage project permissions" onClose={() => setEditing(null)}><form className="permission-modal-form" onSubmit={save}><div className="permission-modal-intro"><strong>{editing.name}</strong><span>Choose the project actions this Agent can perform.</span></div><fieldset className="perm-fieldset"><legend>Allowed project actions</legend>{projectPermissions.map((item) => <label className="checkbox-label" key={item.key}><input type="checkbox" name={`perm-${item.key}`} defaultChecked={editing.permissions?.includes(item.key)} /><span><strong>{item.label}</strong><small>{item.key}</small></span></label>)}</fieldset><button className="primary-button" type="submit">Save permissions</button></form></Modal>}</>;
}
